import gpa

gpa.add_course(3.3,4)
gpa.add_course(4.0)
gpa.add_course(3.7)
gpa.add_course(3.7)
gpa.add_course(3.7)
gpa.add_course(4.0)
gpa.add_course(4.0)
gpa.add_course(4.0)
gpa.add_course(3.7)
gpa.add_course(3.7)
gpa.add_course(4.0)
gpa.add_course(4.0)
gpa.add_course(3.7)
gpa.add_course(4.0)
gpa.add_course(4.0)
gpa.add_course(4.0)
gpa.add_course(4.0)
gpa.add_course(4.0)
gpa.add_course(4.0)
gpa.add_course(4.0)

print(gpa.gpa())